# Generated by Django 3.2.8 on 2021-10-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteReciclador',
            fields=[
                ('idreciclador', models.UUIDField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=70)),
                ('contrasena', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=70)),
                ('direccion', models.CharField(max_length=100)),
                ('recipuntos', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cliente_reciclador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleTransaccionCompra',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('cantproducto', models.IntegerField()),
                ('totalrecipuntosdetalle', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_transaccion_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleTransaccionVenta',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('cantproducto', models.IntegerField()),
                ('totalrecipuntosdetalle', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_transaccion_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Domiciliario',
            fields=[
                ('iddomiciliario', models.UUIDField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=70)),
                ('contraseña', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=100)),
                ('cedula', models.BigIntegerField()),
                ('tipovehiculo', models.CharField(blank=True, max_length=40, null=True)),
                ('cantomicilios', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'domiciliario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idpago', models.UUIDField(primary_key=True, serialize=False)),
                ('mes', models.IntegerField()),
                ('año', models.IntegerField()),
                ('valorpago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalrecipuntos', models.IntegerField()),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoDePrimeraNecesidad',
            fields=[
                ('idproducto', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('descripcion', models.CharField(blank=True, max_length=2000, null=True)),
                ('dirimagen', models.CharField(max_length=100)),
                ('preciopesos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recipuntosporgramos', models.IntegerField()),
            ],
            options={
                'db_table': 'producto_de_primera_necesidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoDeReciclaje',
            fields=[
                ('idreciclaje', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('descripción', models.CharField(blank=True, max_length=2000, null=True)),
                ('dirimagen', models.CharField(max_length=100)),
                ('preciopesos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recipuntosporgamo', models.IntegerField()),
            ],
            options={
                'db_table': 'producto_de_reciclaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablaPagos',
            fields=[
                ('minrecipuntos', models.IntegerField(primary_key=True, serialize=False)),
                ('maxrecipuntos', models.IntegerField()),
                ('pago', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'tabla_pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransaccionCompra',
            fields=[
                ('idtransaccioncompra', models.UUIDField(primary_key=True, serialize=False)),
                ('totalrecipuntostransaccion', models.IntegerField()),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'transaccion_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransaccionVenta',
            fields=[
                ('idtransaccionventa', models.UUIDField(primary_key=True, serialize=False)),
                ('totalrecipuntostransaccion', models.IntegerField()),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'transaccion_venta',
                'managed': False,
            },
        ),
    ]
